

T_cam_lidar: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1,0,0,0,
        0,1,0,0,
        0,0,1,0,
        0,0,0,1]
CameraK: !!opencv-matrix
  rows: 3
  cols: 3
  dt: f
  data: [400,0,400,0,400,400,0,0,1]



